Verify vagrant up strerr is being captured

diff --git a/.github/workflows/virtualbox-vm.yml b/.github/workflows/virtualbox-vm.yml
--- a/.github/workflows/virtualbox-vm.yml
+++ b/.github/workflows/virtualbox-vm.yml
@@ -53,14 +53,14 @@ jobs:
             ~/.vagrant.d/boxes/focal-server-cloudimg-amd64-vagrant
           key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
 
-      - name: Validate Vagrantfile
-        run: vagrant validate
-
-      - name: Lint provision.sh
-        run: |
-          brew install shellcheck
-          shellcheck provision.sh
-          shellcheck self-test/*.sh
+#      - name: Validate Vagrantfile
+#        run: vagrant validate
+#
+#      - name: Lint provision.sh
+#        run: |
+#          brew install shellcheck
+#          shellcheck provision.sh
+#          shellcheck self-test/*.sh
 
       - name: Vagrant up
         id: vagrant-up
@@ -78,9 +78,10 @@ jobs:
         env:
           VAGRANT_ERROR_OUTPUT: ${{ steps.vagrant-up.outputs.stderr }}
         run: |
-          HAS_DOCKER_RATE_LIMIT_ERROR=$(echo "$VAGRANT_ERROR_OUTPUT"| grep "toomanyrequests" | grep -o "docker.com/increase-rate-limit" | wc -l)
+          echo "$VAGRANT_ERROR_OUTPUT"
+          #HAS_DOCKER_RATE_LIMIT_ERROR=$(echo "$VAGRANT_ERROR_OUTPUT"| grep "toomanyrequests" | grep -o "docker.com/increase-rate-limit" | wc -l)
 
-          if [0 -eq $HAS_DOCKER_RATE_LIMIT_ERROR]; then
-            echo "$VAGRANT_ERROR_OUTPUT"
-            exit 1
-          fi
+          #if [0 -eq $HAS_DOCKER_RATE_LIMIT_ERROR]; then
+          #  echo "$VAGRANT_ERROR_OUTPUT"
+          #  exit 1
+          #fi
